[[gitignore]]
sources = ["base.ignore", "latex.ignore"]
target = ".gitignore"

[[latexmkrc]]
sources = ["base.pl", "lualatex.pl"]
target = "examples/.latexmkrc"

[[license]]
sources = ["mit.txt"]
target = "license.txt"
